package install

import (
	"bytes"
	"context"
	"encoding/xml"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/url"
	"strings"
	"time"
)

const (
	wsdAddressingNamespace       = "http://schemas.xmlsoap.org/ws/2004/08/addressing"
	wsdTransferGetAction         = "http://schemas.xmlsoap.org/ws/2004/09/transfer/Get"
	wsdTransferGetResponseAction = wsdTransferGetAction + "Response"
	wsdMetadataMaxBytes          = 1 << 20
)

type wsdMetadataHosted struct {
	Endpoint struct {
		Address string `xml:"http://schemas.xmlsoap.org/ws/2004/08/addressing Address"`
	} `xml:"http://schemas.xmlsoap.org/ws/2004/08/addressing EndpointReference"`
	ServiceID string `xml:"http://schemas.xmlsoap.org/ws/2006/02/devprof ServiceId"`
}

type wsdMetadataRelationship struct {
	Type string `xml:"Type,attr"`
	Host struct {
		Endpoint struct {
			Address string `xml:"http://schemas.xmlsoap.org/ws/2004/08/addressing Address"`
		} `xml:"http://schemas.xmlsoap.org/ws/2004/08/addressing EndpointReference"`
	} `xml:"http://schemas.xmlsoap.org/ws/2006/02/devprof Host"`
	Hosted []wsdMetadataHosted `xml:"http://schemas.xmlsoap.org/ws/2006/02/devprof Hosted"`
}

type wsdMetadataEnvelope struct {
	XMLName xml.Name `xml:"http://www.w3.org/2003/05/soap-envelope Envelope"`
	Header  struct {
		Action    string `xml:"http://schemas.xmlsoap.org/ws/2004/08/addressing Action"`
		RelatesTo string `xml:"http://schemas.xmlsoap.org/ws/2004/08/addressing RelatesTo"`
	} `xml:"http://www.w3.org/2003/05/soap-envelope Header"`
	Body struct {
		Metadata struct {
			Sections []struct {
				Relationship wsdMetadataRelationship `xml:"http://schemas.xmlsoap.org/ws/2006/02/devprof Relationship"`
			} `xml:"http://schemas.xmlsoap.org/ws/2004/09/mex MetadataSection"`
		} `xml:"http://schemas.xmlsoap.org/ws/2004/09/mex Metadata"`
	} `xml:"http://www.w3.org/2003/05/soap-envelope Body"`
}

func wsdMetadataRequest(deviceID, messageID string) []byte {
	// Both values are validated UUID URNs generated by this process or read from
	// WSDMON, so they cannot add XML markup to the request.
	return []byte(fmt.Sprintf(`<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="%s"><s:Header><a:To>%s</a:To><a:Action>%s</a:Action><a:MessageID>%s</a:MessageID><a:ReplyTo><a:Address>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</a:Address></a:ReplyTo></s:Header><s:Body/></s:Envelope>`, wsdAddressingNamespace, deviceID, wsdTransferGetAction, messageID))
}

func wsdMetadataServiceMatches(serviceID, deviceID string) bool {
	value := strings.ToLower(strings.TrimSpace(serviceID))
	value = strings.TrimPrefix(value, "uri:")
	value, _, _ = strings.Cut(value, "/")
	identity, err := normalizeWSDDeviceID(value)
	return err == nil && identity == deviceID
}

func sameWSDMetadataHost(left, right string) bool {
	leftIP, rightIP := net.ParseIP(left), net.ParseIP(right)
	if leftIP != nil || rightIP != nil {
		return leftIP != nil && rightIP != nil && leftIP.Equal(rightIP)
	}
	return strings.EqualFold(left, right)
}

func validateWSDMetadataResponse(payload []byte, location *url.URL, deviceID, messageID string) error {
	var response wsdMetadataEnvelope
	if err := xml.Unmarshal(payload, &response); err != nil {
		return fmt.Errorf("decode WSD metadata: %w", err)
	}
	if strings.TrimSpace(response.Header.Action) != wsdTransferGetResponseAction {
		return errors.New("WSD metadata response has the wrong SOAP action")
	}
	if !strings.EqualFold(strings.TrimSpace(response.Header.RelatesTo), messageID) {
		return errors.New("WSD metadata response does not match the request")
	}
	for _, section := range response.Body.Metadata.Sections {
		relationship := section.Relationship
		if relationship.Type != "http://schemas.xmlsoap.org/ws/2006/02/devprof/host" {
			continue
		}
		rootID, err := normalizeWSDDeviceID(relationship.Host.Endpoint.Address)
		hostIdentified := err == nil && rootID == deviceID
		for _, hosted := range relationship.Hosted {
			if !hostIdentified && !wsdMetadataServiceMatches(hosted.ServiceID, deviceID) {
				continue
			}
			address, err := url.Parse(strings.TrimSpace(hosted.Endpoint.Address))
			if err != nil || (address.Scheme != "http" && address.Scheme != "https") || address.User != nil || address.Hostname() == "" {
				continue
			}
			if sameWSDMetadataHost(address.Hostname(), location.Hostname()) {
				return nil
			}
		}
	}
	return errors.New("WSD metadata has no matching device identity and hosted address")
}

// verifyWSDMetadata asks the device at Windows' cached PnP location for live
// metadata. Its response must name the WSDMON device and a service on the same
// host before that cached location can be used for an IP printer conversion.
func verifyWSDMetadata(ctx context.Context, locationURL, deviceID string) error {
	identity, err := normalizeWSDDeviceID(deviceID)
	if err != nil {
		return err
	}
	location, err := url.Parse(strings.TrimSpace(locationURL))
	if err != nil || (location.Scheme != "http" && location.Scheme != "https") || location.User != nil || location.Hostname() == "" {
		return fmt.Errorf("WSD PnP location %q is not an HTTP device address", locationURL)
	}
	messageID, err := wsdMessageID()
	if err != nil {
		return err
	}
	request, err := http.NewRequestWithContext(ctx, http.MethodPost, location.String(), bytes.NewReader(wsdMetadataRequest(identity, messageID)))
	if err != nil {
		return err
	}
	request.Header.Set("Content-Type", "application/soap+xml; charset=utf-8")
	client := &http.Client{
		Timeout:       8 * time.Second,
		CheckRedirect: func(*http.Request, []*http.Request) error { return http.ErrUseLastResponse },
	}
	response, err := client.Do(request)
	if err != nil {
		return fmt.Errorf("request live WSD metadata: %w", err)
	}
	defer response.Body.Close()
	if response.StatusCode != http.StatusOK {
		return fmt.Errorf("WSD metadata request returned HTTP %d", response.StatusCode)
	}
	payload, err := io.ReadAll(io.LimitReader(response.Body, wsdMetadataMaxBytes+1))
	if err != nil {
		return fmt.Errorf("read WSD metadata: %w", err)
	}
	if len(payload) > wsdMetadataMaxBytes {
		return errors.New("WSD metadata response is too large")
	}
	return validateWSDMetadataResponse(payload, location, identity, messageID)
}
